AWSTemplateFormatVersion: 2010-09-09
Description: Static Site Website Template
Parameters:
  ApplicationName:
    Type: String
    Description: Application name for this project

  AcmCertificateArn:
    Type: String
    Description: The amazon resource name of the acm

  StorageBucket:
    Description: Storage bucket
    Type: AWS::SSM::Parameter::Value<String>

Resources:
  CloudFrontOriginAccessIdentity:
    Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
    Properties:
      CloudFrontOriginAccessIdentityConfig:
        Comment: "S3Origin"

  MainS3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StorageBucket}.s3.amazonaws.com/modules/s3/template.yaml 
      TimeoutInMinutes: 60
      Parameters:
        BucketName: !Ref ApplicationName
        CloudFrontOriginAccessIdentity: !GetAtt CloudFrontOriginAccessIdentity.S3CanonicalUserId

  RedirectS3Bucket:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StorageBucket}.s3.amazonaws.com/modules/s3/redirect-template.yaml 
      TimeoutInMinutes: 60
      Parameters:
        BucketName: !Ref ApplicationName

  CloudfrontDistribution:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: !Sub https://${StorageBucket}.s3.amazonaws.com/modules/cloudfront/template.yaml 
      TimeoutInMinutes: 60
      Parameters:
        AcmCertificateArn: !Ref AcmCertificateArn
        ApplicationName: !Ref ApplicationName
        DomainName: !GetAtt MainS3Bucket.Outputs.MainS3BucketDomainName
        CloudFrontOriginAccessIdentity: !Ref CloudFrontOriginAccessIdentity

  WebsiteDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${ApplicationName}.
      Comment: !Sub Record Set For The Cloudfront For ${ApplicationName}
      Type: A
      Name: !Ref ApplicationName
      AliasTarget:
        DNSName: !GetAtt CloudfrontDistribution.Outputs.DomainName
        HostedZoneId: Z2FDTNDATAQYW2

  RedirectWebsiteDnsRecord:
    Type: AWS::Route53::RecordSet
    Properties:
      HostedZoneName: !Sub ${ApplicationName}.
      Comment: !Sub Record Set For The Cloudfront For www.${ApplicationName}
      Type: A
      Name: !Sub www.${ApplicationName}
      AliasTarget:
        DNSName: !GetAtt RedirectS3Bucket.Outputs.RedirectBucketDomainName
        HostedZoneId: Z3GKZC51ZF0DB4